version: "3.5"
services:
  nginx:
    container_name: nginx
    image: nginx
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./:/code:delegated
    ports:
      - 80:80
    networks:
      - nginx
    depends_on:
      - php
      - mysql
  php:
    container_name: php
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    working_dir: /code
    volumes:
      - ./:/code:delegated
    networks:
      - nginx
    depends_on:
      - mysql
  mysql:
    container_name: my_sql
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - 3306:3306
    networks:
      - nginx
    volumes:
      - mysql_data:/var/lib/mysql
  rabbitmq_1:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq1
    hostname: rabbitmq1
#    volumes:
#      - rabbit_data_1:/var/lib/rabbitmq/
#      - ./docker/rabbitmq/logs_1/:/var/log/rabbitmq/
    environment:
      RABBITMQ_ERLANG_COOKIE: ${RABBITMQ_ERLANG_COOKIE}
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - nginx
  rabbitmq_2:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq2
    hostname: rabbitmq2
#    volumes:
#      - rabbit_data_2:/var/lib/rabbitmq/
#      - ./docker/rabbitmq/logs_2/:/var/log/rabbitmq/
    environment:
      RABBITMQ_ERLANG_COOKIE: ${RABBITMQ_ERLANG_COOKIE}
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    ports:
      - 5673:5672
      - 15673:15672
    networks:
      - nginx

  rabbitmq_3:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq3
    hostname: rabbitmq3
    #    volumes:
    #      - rabbit_data_2:/var/lib/rabbitmq/
    #      - ./docker/rabbitmq/logs_2/:/var/log/rabbitmq/
    environment:
      RABBITMQ_ERLANG_COOKIE: ${RABBITMQ_ERLANG_COOKIE}
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    ports:
      - 5674:5672
      - 15674:15672
    networks:
      - nginx


networks:
  nginx:
    driver: bridge
volumes:
  mysql_data:
  rabbit_data_1:
  rabbit_data_2:
